"""
LLM (Large Language Model) service operations.
"""
import uuid
import replicate
from backend.database import db


def generate_conversation_id() -> str:
    """
    Generates a unique conversation identifier.

    This function creates a unique identifier for a conversation using a UUID
    (Universally Unique Identifier). It ensures the generated ID is globally
    unique.

    :returns: A unique string identifier for a conversation.
    :rtype: str
    """
    return str(uuid.uuid4())


async def generate_llm_response(prompt: str, temperature: float, top_p: float, system_prompt: str, model: str) -> str:
    """
    Generates a response from a Large Language Model (LLM) using the specified parameters. This
    function connects to and utilizes a specified LLM model through the Replicate API,
    allowing users to customize the response generation process with additional
    parameters like temperature, top_p, and a system-level prompt. The function
    supports generating responses up to the limit of 1024 tokens in a single call.

    Any errors during the response generation will result in a fallback message,
    informing the user about the failure.

    :param prompt: The main input text that the LLM will use to generate its response.
    :param temperature: A parameter affecting randomness in responses. Higher values
        translate to more creative and diverse outputs, while lower values produce
        more deterministic completions.
    :param top_p: Controls nucleus sampling for response generation. The LLM considers
        the smallest subset of words whose cumulative probability exceeds `top_p`.
    :param system_prompt: A system-wide prompt applied to the LLM setting additional
        context or constraints for response generation.
    :param model: The identifier of the LLM model to be used from the Replicate service.
    :return: A synthesized text response generated by the LLM model.
    """
    try:
        # Use Meta's Llama model through Replicate
        output = replicate.run(
            model,
            input={
                "prompt": prompt,
                "temperature": temperature,
                "top_p": top_p,
                "max_tokens": 1024,
                "system_prompt": system_prompt,
            }
        )
        print("\n".join([
            f"LLM Input:",
            f"  model = {model}",
            f"  temp = {temperature}",
            f"  top_p = {top_p}",
            f"  system_prompt = {system_prompt}",
            "  prompt:",
            prompt
        ]))

        # Replicate returns a generator, collect all parts of the streamed response
        return "".join(output)
    except Exception as e:
        print(f"Error generating response: {str(e)}")
        return "I apologize, but I encountered an error generating a response."


async def get_conversation_context(conversation_id: str, limit: int = 5) -> str:
    """
    Retrieve the context of a conversation based on a given conversation ID and
    optional limit on the number of messages. The messages are fetched in
    descending order of time and then reversed to construct the context in
    correct chronological order.

    The method builds a context string by iterating through the fetched messages
    and combining their role names and contents. The resulting string represents
    the ordered conversation history.

    :param conversation_id: Unique identifier for the conversation.
    :type conversation_id: str
    :param limit: Maximum number of messages to include in the context. Defaults to 5.
    :type limit: int
    :return: A formatted string containing conversation history with role names and contents in chronological order. If an error occurs, an empty string is returned.
    :rtype: str
    """
    try:
        # Get recent messages using CRUD method (returns in DESC order)
        messages = db.get_recent_messages_for_context(conversation_id, limit)

        # Build context string by joining messages (reverse for chronological order)
        context = []
        for msg in reversed(messages):
            context.append(f"{msg['roleName']}: {msg['content']}")

        return "\n".join(context)
    except Exception as e:
        print(f"Error getting conversation context: {str(e)}")
        return ""
