import trustme
import time
from fastapi import FastAPI, HTTPException, Response, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from dotenv import load_dotenv, find_dotenv
from pathlib import Path
from tinydb import TinyDB, Query


# Error response model
class ErrorResponse(BaseModel):
    error: str


# Pydantic models for request validation
class ConversationState(BaseModel):
    id: int
    hashsum: int


class ApiConversationsCheck(BaseModel):
    conversations: list[ConversationState]


class ApiMessageSend(BaseModel):
    conversationId: int
    roleName: str
    content: str
    time: int


class ApiMessageGenerate(BaseModel):
    conversationId: int
    participant: str
    lastTimestamp: int


class MessagePatch(BaseModel):
    id: int
    conversationId: int
    content: str


# Initialize TinyDB
db = TinyDB('mockup_db.json')
messages = db.table('messages')
Message = Query()


# Setup FastAPI app
app = FastAPI()


# Generate and save development certificates using trustme.
def setup_development_certificates():
    # Create a certificate authority
    ca = trustme.CA()
    
    # Generate server cert with localhost DNS name
    server_cert = ca.issue_cert("localhost")

    # Create a temporary directory for certificates if it doesn't exist
    cert_dir = Path("devcerts")
    cert_dir.mkdir(exist_ok=True)
    
    # Save the certificates
    server_cert.private_key_and_cert_chain_pem.write_to_path(cert_dir / "server.pem")
    server_cert.private_key_pem.write_to_path(cert_dir / "server.key")
    ca.cert_pem.write_to_path(cert_dir / "ca.pem")
    
    return str(cert_dir / "server.pem"), str(cert_dir / "server.key")


# Generate a hashsum from the conversation messages
def generate_hash(messages: list) -> int:
    """
    Custom hashsum generator for checking the integrity of a conversation.
    The hashsum is generated by summing up the first, last character codes plus the length.
     
    
    Args:
        messages (list): List of message objects

    Returns:
        int: A integer value representing the hashsum
    """
    if not messages:
        return 0
    else:
        hash_value = 0
        hash_chars = ""

    for message in messages:
        content = message.get('content', '')
        if not content:
            hash_value += 0
            continue

        # Add character codes and length
        hash_value += ord(content[0])
        hash_value += ord(content[-1])
        hash_value += len(content)

        # Note chars for debugging
        hash_chars += content[0] + content[-1] + str(len(content))

    # Use modulo to stay within safe integer range
    hash_value %= (2**32)

    print(f"Generated hashsum: {hash_value} string rep: {hash_chars}")
    return hash_value


# Mock endpoints for debugging purposes
@app.post("/api/conversation/check")
async def check_conversations(request: ApiConversationsCheck, response: Response, status_code=status.HTTP_204_NO_CONTENT):
    print("Refresh conversation called")

    print(request)
    print(request.conversations)

    try:
        # Error case
        if not ApiConversationsCheck:
            response.status_code = status.HTTP_400_BAD_REQUEST
            return ErrorResponse(error="Conversations are missing")
        
        conversations = []

        # Iterate over the conversations and check for new messages
        for conversation in request.conversations:
            messages = db.search(Message.conversationId == conversation.id)
            hashsum = generate_hash(messages)

            # Add the last 20 messages to the response if the hashsum don't match
            if conversation.hashsum != hashsum:
                conversations.append({
                    'id': conversation.id,
                    'messages': messages[-20:] 
                })

        # Success case
        if len(conversations) > 0:
            response.status_code = status.HTTP_200_OK
            return conversations

        # Return no content if no new messages (204 No Content)
        return None
        
    except Exception as e:
        response.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        return ErrorResponse(error=str(e))


@app.get("/api/conversation/load/{conversation_id}/{timestamp}/{messages_count}")
async def refresh_conversation(conversation_id, timestamp, messages_count, response: Response, status_code=status.HTTP_200_OK):
    print("Refresh conversation called")

    try:
        # Error case
        if not conversation_id and timestamp:
            response.status_code = status.HTTP_400_BAD_REQUEST
            return ErrorResponse(error="Conversation ID and latest timestamp are required")

        # Load the messages before the timestamp
        messages = db.search(
            (Message.conversationId == conversation_id) & 
            (Message.time < timestamp)
        )
            
        # Success case
        if len(messages) > 0:
            if messages_count > 30 & messages > 30:
                # Limit the messages to 30
                messages_count = 30
                response.status_code = status.HTTP_206_PARTIAL_CONTENT
                return messages[-messages_count:]
            else:
                # Return the messages
                response.status_code = status.HTTP_200_OK
                return messages[-messages_count:]
        else:
            # Return no content if no messages found
            response.status_code = status.HTTP_204_NO_CONTENT
            return None
        
    except Exception as e:
        response.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        return ErrorResponse(error=str(e))


@app.post("/api/message/send")
async def user_send_message(request: ApiMessageSend, response: Response, status_code=status.HTTP_200_OK):
    print("Message send called")

    try:
        # Error case
        if not request.content:
            response.status_code = status.HTTP_400_BAD_REQUEST
            return ErrorResponse(error="Message content cannot be empty")

        # Success case
        message_id = int(time.time() * 1000)

        # Insert a message document into database
        messages.insert({
            'id': message_id,
            'conversationId': request.conversationId,
            'roleName': request.roleName,
            'content': request.content,
            'time': request.time
        })
        
        response.status_code = status.HTTP_201_CREATED
        return {"id": message_id}
        
    except Exception as e:
        response.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        return ErrorResponse(error=str(e))


@app.post("/api/message/generate")
async def generate_message(request: ApiMessageGenerate, response: Response, status_code=status.HTTP_200_OK):
    print("Generate message called")
    # TODO: Make the request also send the conversation hash to check if anything changed (has still required since the user could have changed earlier messages on another device!)

    try:
        # Error case
        if not request:
            response.status_code = status.HTTP_400_BAD_REQUEST
            return ErrorResponse(error="Conversation ID missing")

        # Success case
        message_doc = {
            'id': int(time.time() * 1000),
            'conversationId': request.conversationId,
            'roleName': request.roleName,
            'content': "This is a mock response from the backend!",
            'time': int(time.time() * 1000)
            # 'time': request.lastTimestamp + 100
        }

        # Insert the message document into database
        messages.insert(message_doc)
        
        response.status_code = status.HTTP_201_CREATED
        return message_doc
        
    except Exception as e:
        response.status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        return ErrorResponse(error=str(e))


@app.patch("/api/message/patch")
async def patch_message(request: MessagePatch, status_code=status.HTTP_200_OK):
    print("Patch message called")

    try:
        if not request.id:
            return Response(status_code=status.HTTP_400_BAD_REQUEST)
        
        # Success case updates the message and returns an empty response
        messages.update(
            {'content': request.content},
            (Message.conversationId == request.conversationId) &
            (Message.id == request.id)
        )

        # Return with default status code (200 OK)
        return None
        
    except Exception as e:
        return Response(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR)


@app.delete("/api/message/delete/{conversation_id}/{message_id}")
async def delete_message(conversation_id: str, message_id: str, status_code=status.HTTP_200_OK):
    print("Delete message called")

    try:
        if not conversation_id and not message_id:
            return Response(status_code=status.HTTP_400_BAD_REQUEST)
        
        # Success case removes the message and returns an empty response
        messages.remove(
            (Message.conversationId == int(conversation_id)) & 
            (Message.messageId == int(message_id))
        )
        
        # Return with default status code (200 OK)
        return None
        
    except Exception as e:
        return Response(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR)


# load_dotenv(find_dotenv())
# dev_certs = os.getenv("DEV_CERTS", "True")
dev_certs = "True"

# Enable CORS
origins = [
    "http://localhost:4200",      # Angular dev server
    "http://localhost:8080",      # Alternative dev port
    "https://localhost:4200",     # In case you run Angular with SSL
    "https://localhost:8080",     # Alternative SSL port
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
    expose_headers=["*"]  # Exposes all headers
)

# Check if we're in development mode
if dev_certs == "True":
    print("Starting in development mode with auto-generated certificates...")
    cert_file, key_file = setup_development_certificates()

    print(f"""
    🔐 Development HTTPS certificates generated!
    
    To trust these certificates in development:
    1. Certificate file location: {cert_file}
    2. You might need to add an exception in your browser
    3. For Angular development, you might need to set NODE_TLS_REJECT_UNAUTHORIZED='0'
    
    ⚠️  These are self-signed certificates for development only!
    """)
    
    ssl_config = {
        "ssl_keyfile": key_file,
        "ssl_certfile": cert_file,
    }
else:
    # Production certificate paths
    ssl_config = {}
